/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.airline;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Shreyas V Shetty
 */
public class Print_Report extends javax.swing.JInternalFrame {

    /**
     * Creates new form Print_Report
     */
    String TNO;
    public Print_Report(String TNO) {
        initComponents();
        this.TNO=TNO;
        ticket();
    }
    Connection con;
    PreparedStatement pre;
    
    public void ticket()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/airlinedb","root","8970");
            pre=con.prepareStatement("select * from airlinedb.tickets where Ticket_NO=?");
            pre.setString(1,TNO);
            ResultSet rs=pre.executeQuery();
            rs.next();
            pre=con.prepareStatement("select * from airlinedb.customer where CustomerID=?");
            pre.setString(1,rs.getString("Customer_ID"));
            ResultSet rs1=pre.executeQuery();
            rs1.next();
            pre=con.prepareStatement("select * from airlinedb.flights where Flight_ID=?");
            pre.setString(1,rs.getString("Flight_ID"));
            ResultSet rs2=pre.executeQuery();
            rs2.next();
            
            
            
            
            TextArea.setText("-------------------------------------------------------------------------------------------------------------------------\n");
            TextArea.setText(TextArea.getText()+"                                                                   Ticket Details\n");
            TextArea.setText(TextArea.getText()+"-------------------------------------------------------------------------------------------------------------------------\n");
            TextArea.setText(TextArea.getText()+"    Ticket NO     : "+rs.getString("Ticket_NO")+"                          Customer ID : "+rs1.getString("CustomerID")+"                             Flight ID : "+rs2.getString("Flight_ID")+"\n\n");
            TextArea.setText(TextArea.getText()+"    Customer Name : "+rs1.getString("First_Name")+" "+rs1.getString("Last_Name")+"                  Gender : "+rs1.getString("Gender")+"                                  Passport : "+rs1.getString("Passport")+"\n\n");
            TextArea.setText(TextArea.getText()+"    Nic ID : "+rs1.getString("Nic")+"                                           D.O.B : "+rs1.getString("DOB")+"                                Contact : "+rs1.getString("Contact")+"\n\n");
            TextArea.setText(TextArea.getText()+"    Flight Name : "+rs2.getString("Flight_Name")+"                                Source : "+rs2.getString("Source")+"                  Destination : "+rs2.getString("Destination")+"\n\n");
            TextArea.setText(TextArea.getText()+"    Fare : "+ "RS. "+rs2.getString("Fare")+"                                       Date : "+rs2.getString("Date")+   "                          No of tickets : "+rs.getString("No_of_tickets")+"\n\n");
            TextArea.setText(TextArea.getText()+"    Arrival Time : "+rs2.getString("Arrival_Time")+"                            Departure Time : "+rs2.getString("Departure_Time")+"                  Total Amount : "+"RS. "+String.valueOf(Integer.parseInt(rs2.getString("Fare"))*Integer.parseInt(rs.getString("No_of_tickets")))+"\n\n");
        } catch (ClassNotFoundException |SQLException ex) {
            Logger.getLogger(Print_Report.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ticket Details");

        TextArea.setEditable(false);
        TextArea.setColumns(20);
        TextArea.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TextArea.setRows(5);
        TextArea.setPreferredSize(new java.awt.Dimension(100, 100));
        jScrollPane1.setViewportView(TextArea);

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jButton1)
                        .addGap(93, 93, 93)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            TextArea.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Print_Report.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
